language: python

python:
  - 3.6

services: sqlite3

env:
  - DJANGO=2.0.4

before_install:
#  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PYTHONPATH=$HOME/builds/olb/django1
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U sqlite3

script:
  - python manage.py syncdb --noinput
